name: Coverity Scan

on:
    workflow_run:
        workflows: ["Scan and publish"]
        types:
            - completed

jobs:
    coverity_scan:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2