name: Coverity Scan

on:
    workflow_dispatch: # Manually trigger the workflow (due to limitations of free tier)

jobs:
    coverity_scan:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Download dependencies
          run: |
            sudo apt-get update && sudo apt-get install -y \
                g++ \
                make \
                cmake \
                libssl-dev \
                pkg-config \
                build-essential \
                nlohmann-json3-dev \
                && sudo rm -rf /var/lib/apt/lists/*

        - name: Setup Coverity
          run: |
            curl --silent --output coverity_tool.tgz --data "token=${{ secrets.COV_PROJECT_TOKEN }}&project=${{ secrets.COV_ORG }}" \
                https://scan.coverity.com/download/linux64 
            tar -xzf coverity_tool.tgz 
            
            COVERITY_DIR=$(find . -type d -name "cov-analysis-linux64-*")
            echo -e "\n################ DOWNLOAD SUCCESS ################"
            
            echo "COVERITY_DIR=$COVERITY_DIR" >> $GITHUB_ENV
            echo -e "\nSetting up permission for Coverity file saved in $COVERITY_DIR"
            chmod +x $COVERITY_DIR/bin/*
            echo -e "\n################ SETUP SUCCESS ################"
          
        - name: Build with Coverity
          run: |
            mkdir -p cov-int
            ${{ env.COVERITY_DIR }}/bin/cov-build --dir cov-int \
                g++ -static -static-libgcc -static-libstdc++ -I include src/*.cpp app/main.cpp -lssl -lcrypto -o fortresses

        - name: Compress Results
          run: tar czvf analysis.tar.gz cov-int

        - name: Upload to Coverity
          run: |
            curl --form token=${{ secrets.COV_PROJECT_TOKEN }} \
                --form email=${{ secrets.COV_ADMIN }} \
                --form file=@analysis.tar.gz \
                --form version="1.0" \
                --form description="Code Scan" \
                https://scan.coverity.com/builds?project=${{ secrets.COV_ORG }}