name: Scan and publish

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:

  create_artifact:
    name: Build Artifact
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
          g++ \
          make \
          cmake \
          libssl-dev \
          pkg-config \
          build-essential \
          nlohmann-json3-dev \
          && sudo rm -rf /var/lib/apt/lists/*

    - name: Compile code
      run: |
        g++ -static -static-libgcc -static-libstdc++ \
          -I include src/*.cpp app/main.cpp \
          -lssl -lcrypto \
          -o fortresses

    - name: Upload build artifacts
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: fortresses
        path: fortresses

  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    needs: create_artifact

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Set up Ubuntu environment
      run: |
        sudo apt-get update && sudo apt-get install -y \
          g++ \
          make \
          cmake \
          libssl-dev \
          pkg-config \
          build-essential \
          nlohmann-json3-dev \
          && sudo rm -rf /var/lib/apt/lists/*

    - name: Compile code
      run: |
        g++ -static -static-libgcc -static-libstdc++ \
          -I include src/*.cpp app/main.cpp \
          -lssl -lcrypto \
          -o fortresses

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3